### ISSUE TITLE
When registering a new user, it is not linked to a company

### ISSUE THREAD

**Issue by SiteBooster** [andrewdwallo/filament-companies#139] opened 2024-05-06 20:18 UTC
Thanks for your awesome plugin!

I have one minor issue:
When I register a new user I get redirected to the /company/{id}/profile page, which does not exist. When I try to go to the dashboard, I get an error saying  `Missing required parameter for [Route: filament.company.pages.dashboard] [URI: company/{tenant}] [Missing parameter: tenant].`

This error gets thrown because the newly created user is not linked to a company yet. How do I create a new company when a new user is registered?

Thanks in advance!

**Comment by ANJANS** [comment] 2024-05-13 10:09
the same for me. Everything stopped here.

**Comment by andrewdwallo** [comment] 2024-05-14 17:11
When registering a new user, you should automatically be redirected to the create company page after. Does this not happen for you guys?

**Comment by zxhub-llc** [comment] 2024-05-15 03:43
This error appears when I install the package for the first time and go to the following path http://127.0.0.1:8000/company/new
<img width="1680" alt="Screen Shot 2024-05-14 at 22 41 47" src="https://github.com/andrewdwallo/filament-companies/assets/161612251/e0e22caf-7d02-4e2f-9ace-99b3e7874d81">


Is it normal for this error to occur when registering for the first time?

**Comment by zxhub-llc** [comment] 2024-05-15 03:48
> Thanks for your awesome plugin!
> 
> I have one minor issue: When I register a new user I get redirected to the /company/{id}/profile page, which does not exist. When I try to go to the dashboard, I get an error saying `Missing required parameter for [Route: filament.company.pages.dashboard] [URI: company/{tenant}] [Missing parameter: tenant].`
> 
> This error gets thrown because the newly created user is not linked to a company yet. How do I create a new company when a new user is registered?
> 
> Thanks in advance!

@andrewdwallo @SiteBooster @ANJANS 
use Wallo\FilamentCompanies\Pages\User\PersonalAccessTokens;
use Wallo\FilamentCompanies\Pages\User\Profile;
->pages([
                Pages\Dashboard::class,
                Profile::class,
                PersonalAccessTokens::class,
            ])
            
The error I mentioned before was solved by adding this in the panel that is registered for the first time with filament
Is there a way you can avoid having two panels and only use the default one of the plugin?

**Comment by andrewdwallo** [comment] 2024-05-15 23:17
@zxstudio-llc Currently, no. This is because the tenants (user and company) are separated by panels.

**Comment by andrewdwallo** [comment] 2024-05-22 22:21
@SiteBooster Any update after what I said? If not I will be closing this issue.

**Comment by bencurio** [comment] 2024-05-24 15:18
Hi,

It may be related to this issue:

I'm testing with a Laravel 11, I experienced a similar thing. I noticed that `CreateNewUser::class` is not triggered after registration.

FilamentCompaniesServiceProvider.php

```php
    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        $this->configurePermissions();

        FilamentCompanies::createUsersUsing(CreateNewUser::class);
```

CreateNewUser.php

```php
class CreateNewUser implements CreatesNewUsers
{
    /**
     * Create a newly registered user.
     *
     * @param  array<string, string>  $input
     */
    public function create(array $input): User
    {
        Validator::make($input, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
            'terms' => FilamentCompanies::hasTermsAndPrivacyPolicyFeature() ? ['accepted', 'required'] : '',
        ])->validate();

        return DB::transaction(function () use ($input) {
            return tap(User::create([
                'name' => $input['name'],
                'email' => $input['email'],
                'password' => Hash::make($input['password']),
            ]), function (User $user) {
                $this->createCompany($user);
            });
        });
    }

    /**
     * Create a personal company for the user.
     */
    protected function createCompany(User $user): void
    {
        $user->ownedCompanies()->save(Company::forceCreate([
            'user_id' => $user->id,
            'name' => explode(' ', $user->name, 2)[0] . "'s Company",
            'personal_company' => true,
        ]));
    }
}
```

The user is created somewhere else (I guess: `Filament\Pages\Auth\Register`), but it is not created by this trigger.

However, the plugin still works because `/company/new` route is called where the first company can be created by manually.

**Comment by bencurio** [comment] 2024-05-24 15:33
Oh! I think the problem is that you have paste the link code from the readme.

```php
            MenuItem::make()
                ->label('Company')
                ->icon('heroicon-o-building-office')
                ->url(static fn () => url(Pages\Dashboard::getUrl(panel: 'company', tenant: Auth::user()->personalCompany()))),
```

Probably the problem is that it throws an exception, since the company does not exist.

Don't forget that the user profile should be in a separate panel (for example, "app").

**Comment by bencurio** [comment] 2024-05-24 15:38
> This error appears when I install the package for the first time and go to the following path http://127.0.0.1:8000/company/new <img alt="Screen Shot 2024-05-14 at 22 41 47" width="1680" src="https://private-user-images.githubusercontent.com/161612251/330653291-e0e22caf-7d02-4e2f-9ace-99b3e7874d81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjUxMjQsIm5iZiI6MTcxNjU2NDgyNCwicGF0aCI6Ii8xNjE2MTIyNTEvMzMwNjUzMjkxLWUwZTIyY2FmLTdkMDItNGUyZi05YWNlLTk5YjNlNzg3NGQ4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxNTMzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjMwMGQzNGNmOGM1MDdmZmEwM2I2ODNkZjY5NzA0MjBlYmQ3MjBjMzFhZmUwYjkwNjNlZWE5ZDZhMGE2NDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EcWWETISVCUQ7fhvd2bMj-KBCIxjQGfIwh0hFY9ND0I">
> 
> Is it normal for this error to occur when registering for the first time?

For it to work you need to enable the Profile page in the panel.

E.g.:

User Panel:

```php
class AppPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->id('app')
            ->path('app')
            // [...]
            ->pages([
                \Wallo\FilamentCompanies\Pages\User\Profile::class // <------------
            ]);
```

Companies Panel:

```php
class FilamentCompaniesServiceProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->id('company')
            ->path('company')
            // [...]
            ->plugin(
                FilamentCompanies::make()
                    ->userPanel('app') // <------------
```

**Comment by zxhub-llc** [comment] 2024-05-24 15:43
> > This error appears when I install the package for the first time and go to the following path http://127.0.0.1:8000/company/new <img alt="Screen Shot 2024-05-14 at 22 41 47" width="1680" src="https://private-user-images.githubusercontent.com/161612251/330653291-e0e22caf-7d02-4e2f-9ace-99b3e7874d81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjUxMjQsIm5iZiI6MTcxNjU2NDgyNCwicGF0aCI6Ii8xNjE2MTIyNTEvMzMwNjUzMjkxLWUwZTIyY2FmLTdkMDItNGUyZi05YWNlLTk5YjNlNzg3NGQ4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxNTMzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjMwMGQzNGNmOGM1MDdmZmEwM2I2ODNkZjY5NzA0MjBlYmQ3MjBjMzFhZmUwYjkwNjNlZWE5ZDZhMGE2NDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EcWWETISVCUQ7fhvd2bMj-KBCIxjQGfIwh0hFY9ND0I">
> 
> > 
> 
> > Is it normal for this error to occur when registering for the first time?
> 
> 
> 
> For it to work you need to enable the Profile page in the panel.
> 
> 
> 
> E.g.:
> 
> 
> 
> User Panel:
> 
> 
> 
> ```php
> 
> class AppPanelProvider extends PanelProvider
> 
> {
> 
>     public function panel(Panel $panel): Panel
> 
>     {
> 
>         return $panel
> 
>             ->id('app')
> 
>             ->path('app')
> 
>             // [...]
> 
>             ->pages([
> 
>                 \Wallo\FilamentCompanies\Pages\User\Profile::class // <------------
> 
>             ]);
> 
> ```
> 
> 
> 
> Companies Panel:
> 
> 
> 
> ```php
> 
> class FilamentCompaniesServiceProvider extends PanelProvider
> 
> {
> 
>     public function panel(Panel $panel): Panel
> 
>     {
> 
>         return $panel
> 
>             ->id('company')
> 
>             ->path('company')
> 
>             // [...]
> 
>             ->plugin(
> 
>                 FilamentCompanies::make()
> 
>                     ->userPanel('app') // <------------
> 
> ```

Of course this is the main functionality but the objective is to not have a second user panel, but rather to allow you to view the resources that a role can access through roles and permissions.

For now I'm still looking for the option, apparently I think I can achieve it by integrating filament-shield but after installing it you have to make some changes to the files that are installed in the vendor folder

**Comment by bencurio** [comment] 2024-05-24 16:12
I understand that the user interface needs a lot of work to make it clearer to purpose the user panel and the company panel, but it's not worth putting it all in one panel. Maybe consider using clearly visible cross links between the user and company panel functions.

The User Panel provides a higher level of access to your user account, which you should be able to access even if you don't have any company profiles, for example. This is where functions like company creation/management, password change, PAT, etc... It is not recommended to place them on the company panel.

It is worth understanding how the system works before coding. As a first step, I recommend reviewing how [Filament Tenant](https://filamentphp.com/docs/3.x/panels/tenancy) works, especially the tenant relationships.

**Comment by andrewdwallo** [comment] 2024-05-25 19:08
I'm closing this issue due to inactivity.

**Closed as completed by andrewdwallo** 2024-05-25 19:08 UTC
