### ISSUE TITLE
OwnerRole missing description?

### ISSUE THREAD

**Issue by russdot** [andrewdwallo/filament-companies#155] opened 2024-09-12 14:11 UTC
First of all - thanks for this great plugin! It has made developing a multi-tenant app with Filament a breeze.

I am encountering an issue though: When attempting to check the `$user->companyRole($company)` method in the `HasCompanies` trait, I am getting an error for the owner.

Example:
```php
$u = User::find(3); 
$c = $u->currentCompany;

$u->ownsCompany($c); // true

$u->companyRole($c); // causing error (See below)
```

```
Error 

  Typed property Wallo\FilamentCompanies\Role::$description must not be accessed before initialization

  at vendor/andrewdwallo/filament-companies/src/Role.php:62
     58▕     {
     59▕         return [
     60▕             'key' => $this->key,
     61▕             'name' => __($this->name),
  ➜  62▕             'description' => __($this->description),
     63▕             'permissions' => $this->permissions,
     64▕         ];
     65▕     }
     66▕ }

  1   [internal]:0
      Wallo\FilamentCompanies\Role::jsonSerialize()
  2   phar:///Applications/Tinkerwell.app/Contents/Resources/tinkerwell/tinker.phar/src/Actions/CliAction.php:236

```

If I manually just set a description in the `OwnerRole` constructor, it works fine and I get the expected `OwnerRole` returned.
```diff
class OwnerRole extends Role
{
    /**
     * Create a new role instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct('owner', 'Owner', ['*']);
+        $this->description('testing');
    }
}
```

```
Wallo\FilamentCompanies\OwnerRole#4323 ▼
  +key: "owner"
  +name: "Owner"
  +permissions: array:1 [▶
    0 => "*"
  ]
  +description: "testing"

```

**Comment by andrewdwallo** [comment] 2024-09-18 07:13
Thank you for the kind words! I'm glad to hear the plugin has made developing your multi-tenant app easier.

Regarding the issue you're encountering with the `companyRole($company)` method and the error related to accessing the description field for the `OwnerRole`, I want to clarify the intended behavior. The `OwnerRole` is specifically designed for the creator (owner) of the company, and as such, the description field isn’t intended to be used or set. The role should not be assigned to anyone other than the company’s creator, so there’s no need for a description.

### Why the description Isn’t Set

Since the `OwnerRole` is inherently tied to the person who creates the company, it doesn't need to be dynamically assigned to other users, and therefore the description isn’t initialized. Accessing this property, like in your case, can cause the error you're seeing during serialization or certain access patterns.

### Potential Issues with Customizing the `OwnerRole`

Allowing customization of the `OwnerRole` could potentially cause issues within the application. This role is tightly coupled with the logic that identifies the owner of a company, and modifying it could lead to unintended behavior, such as misassigning ownership or allowing non-owners to gain unintended permissions. To maintain the integrity of the ownership logic, the `OwnerRole` is kept as a special role.

### Workaround

That said, I understand this may cause issues in certain use cases where the role object is being serialized. As a workaround, you can manually initialize the description when working with the `OwnerRole` if serialization or accessing the description is required in your specific use case. Here's how you can do that:

```php
class CustomOwnerRole extends OwnerRole
{
    public function __construct()
    {
        parent::__construct();
        $this->description = 'Owner role with full permissions.';
    }
}
```

To apply this in your application, you can bind this custom role in your `AppServiceProvider`:
```php
$this->app->bind(OwnerRole::class, CustomOwnerRole::class);
```

This way, the error will be avoided in scenarios where the description is accessed or serialized.

Again, thank you for reporting this, and I hope this workaround helps. If you have any further questions, feel free to reach out!

**Closed as completed by andrewdwallo** 2024-09-18 07:13 UTC
